# Generated by Django 5.0.14 on 2026-09-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='plataforma',
            field=models.CharField(max_length=200),
        ),
    ]
